## Import Libraries

In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import Data

In [70]:
data = pd.read_csv('customers.csv')

# Read Data

In [71]:
data.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,26-08-2020,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,27-04-2020,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,22-03-2022,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,02-07-2020,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,17-01-2021,https://welch.info/

## This dataset is about Customers and the website where they have subscriptions
### This dataset contains Customer ID, first name, last name, company, city, country, phone 1 and 2, email, subscription date and website where they have subscribed

### last 5 rows

In [72]:
data.tail(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,27-04-2022,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,17-01-2022,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,13-01-2022,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,14-04-2020,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,27-06-2020,http://nixon.net/

### Customer Id is not important, and there might be some issue with the phone number, also the website links are not necessary

# Checking shape

In [73]:
data.shape

(10000, 12)

# Checking columns

In [74]:
data.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='str')

# summary statistics

In [75]:
data.describe()

             Index
count  10000.00000
mean    5000.50000
std     2886.89568
min        1.00000
25%     2500.75000
50%     5000.50000
75%     7500.25000
max    10000.00000

In [76]:
data.describe(include='object')

C:\Users\Gaurav G Methe\AppData\Local\Temp\ipykernel_15668\3382516499.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.describe(include='object')

,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
count,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000
unique,10000,690,1000,9215,8910,243,9993,9992,10000,880,8315
top,EB54EF1154C3A78,Gregg,Dunlap,Keith Inc,Port Marilyn,Korea,-4940,-5766,urangel@espinoza-francis.net,13-04-2020,http://www.cordova.com/
freq,1,25,23,4,4,84,2,2,1,24,6

# Checking missing values

In [77]:
data.isnull().sum()

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

### There is no missing values

In [78]:
(data.isnull().sum()/len(data)) * 100 #Percentage missing

Index                0.0
Customer Id          0.0
First Name           0.0
Last Name            0.0
Company              0.0
City                 0.0
Country              0.0
Phone 1              0.0
Phone 2              0.0
Email                0.0
Subscription Date    0.0
Website              0.0
dtype: float64

# Checking duplicate rows

In [79]:
data.duplicated().sum()

np.int64(0)

### There are no duplicated values

# Checking datatypes

In [80]:
data.dtypes

Index                int64
Customer Id            str
First Name             str
Last Name              str
Company                str
City                   str
Country                str
Phone 1                str
Phone 2                str
Email                  str
Subscription Date      str
Website                str
dtype: object

# Checking information

In [81]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              10000 non-null  int64
 1   Customer Id        10000 non-null  str
 2   First Name         10000 non-null  str
 3   Last Name          10000 non-null  str
 4   Company            10000 non-null  str
 5   City               10000 non-null  str
 6   Country            10000 non-null  str
 7   Phone 1            10000 non-null  str
 8   Phone 2            10000 non-null  str
 9   Email              10000 non-null  str
 10  Subscription Date  10000 non-null  str
 11  Website            10000 non-null  str
dtypes: int64(1), str(11)
memory usage: 937.6 KB

### Phone number is in string, we have to convert it to integer

In [82]:
data_bkp = data #storing backup

In [83]:
data.drop(['Index','Email','Company','Website','Customer Id','Country','Phone 2'], axis=1, inplace=True) #Dropping unnecessary columns

In [84]:
data

,First Name,Last Name,City,Phone 1,Subscription Date
0,Heather,Callahan,Lake Jeffborough,043-797-5229,26-08-2020
1,Kristina,Ferrell,Aaronville,932-062-1802,27-04-2020
2,Briana,Andersen,East Jordan,8352752061,22-03-2022
3,Patty,Ponce,East Kristintown,302.398.3833,02-07-2020
4,Kathleen,Mccormick,Andresmouth,001-184-153-9683x1497,17-01-2021
...,...,...,...,...,...
9995,Meghan,Cline,Petersport,001-270-136-4738x419,27-04-2022
9996,Jeremiah,Pena,Briggsport,+1-531-494-7645x4844,17-01-2022
9997,Peggy,Key,West Joyceport,520.109.2482x26052,13-01-2022
9998,Evan,Humphrey,Camachochester,001-465-242-9979,14-04-2020
9999,Melissa,Montgomery,Sparkstown,+1-889-682-9490x65400,27-06-2020

In [85]:
data['Phone 1'].dtype

In [98]:
data.rename(columns={'Phone 1':'Phone'}, inplace=True) #Renaming column

In [87]:
data

,First Name,Last Name,City,Phone,Subscription Date
0,Heather,Callahan,Lake Jeffborough,043-797-5229,26-08-2020
1,Kristina,Ferrell,Aaronville,932-062-1802,27-04-2020
2,Briana,Andersen,East Jordan,8352752061,22-03-2022
3,Patty,Ponce,East Kristintown,302.398.3833,02-07-2020
4,Kathleen,Mccormick,Andresmouth,001-184-153-9683x1497,17-01-2021
...,...,...,...,...,...
9995,Meghan,Cline,Petersport,001-270-136-4738x419,27-04-2022
9996,Jeremiah,Pena,Briggsport,+1-531-494-7645x4844,17-01-2022
9997,Peggy,Key,West Joyceport,520.109.2482x26052,13-01-2022
9998,Evan,Humphrey,Camachochester,001-465-242-9979,14-04-2020
9999,Melissa,Montgomery,Sparkstown,+1-889-682-9490x65400,27-06-2020

### creating a function to clean phone number

In [88]:
import re
def clean_phone(phone):
    phone = str(phone).split('x')[0]   # Remove extension
    digits = re.sub(r'\D', '', phone)
    return int(digits)

data['Phone'] = data['Phone'].apply(clean_phone)

In [89]:
data

     First Name   Last Name              City        Phone Subscription Date
0       Heather    Callahan  Lake Jeffborough    437975229        26-08-2020
1      Kristina     Ferrell        Aaronville   9320621802        27-04-2020
2        Briana    Andersen       East Jordan   8352752061        22-03-2022
3         Patty       Ponce  East Kristintown   3023983833        02-07-2020
4      Kathleen   Mccormick       Andresmouth  11841539683        17-01-2021
...         ...         ...               ...          ...               ...
9995     Meghan       Cline        Petersport  12701364738        27-04-2022
9996   Jeremiah        Pena        Briggsport  15314947645        17-01-2022
9997      Peggy         Key    West Joyceport   5201092482        13-01-2022
9998       Evan    Humphrey    Camachochester  14652429979        14-04-2020
9999    Melissa  Montgomery        Sparkstown  18896829490        27-06-2020

[10000 rows x 5 columns]

In [90]:
data.value_counts()

First Name  Last Name   City              Phone        Subscription Date
Heather     Callahan    Lake Jeffborough  437975229    26-08-2020           1
Kristina    Ferrell     Aaronville        9320621802   27-04-2020           1
Briana      Andersen    East Jordan       8352752061   22-03-2022           1
Patty       Ponce       East Kristintown  3023983833   02-07-2020           1
Kathleen    Mccormick   Andresmouth       11841539683  17-01-2021           1
                                                                           ..
Meghan      Cline       Petersport        12701364738  27-04-2022           1
Jeremiah    Pena        Briggsport        15314947645  17-01-2022           1
Peggy       Key         West Joyceport    5201092482   13-01-2022           1
Evan        Humphrey    Camachochester    14652429979  14-04-2020           1
Melissa     Montgomery  Sparkstown        18896829490  27-06-2020           1
Name: count, Length: 10000, dtype: int64

In [91]:
data.insert(0,
           'Full Name',
            data['First Name'] + ' ' + data['Last Name']
           ) #Creating new column

In [92]:
data

,Full Name,First Name,Last Name,City,Phone,Subscription Date
0,Heather Callahan,Heather,Callahan,Lake Jeffborough,437975229,26-08-2020
1,Kristina Ferrell,Kristina,Ferrell,Aaronville,9320621802,27-04-2020
2,Briana Andersen,Briana,Andersen,East Jordan,8352752061,22-03-2022
3,Patty Ponce,Patty,Ponce,East Kristintown,3023983833,02-07-2020
4,Kathleen Mccormick,Kathleen,Mccormick,Andresmouth,11841539683,17-01-2021
...,...,...,...,...,...,...
9995,Meghan Cline,Meghan,Cline,Petersport,12701364738,27-04-2022
9996,Jeremiah Pena,Jeremiah,Pena,Briggsport,15314947645,17-01-2022
9997,Peggy Key,Peggy,Key,West Joyceport,5201092482,13-01-2022
9998,Evan Humphrey,Evan,Humphrey,Camachochester,14652429979,14-04-2020
9999,Melissa Montgomery,Melissa,Montgomery,Sparkstown,18896829490,27-06-2020

In [93]:
data.drop(['First Name', 'Last Name'], axis=1, inplace=True) # Dropping columns
data

               Full Name              City        Phone Subscription Date
0       Heather Callahan  Lake Jeffborough    437975229        26-08-2020
1       Kristina Ferrell        Aaronville   9320621802        27-04-2020
2        Briana Andersen       East Jordan   8352752061        22-03-2022
3            Patty Ponce  East Kristintown   3023983833        02-07-2020
4     Kathleen Mccormick       Andresmouth  11841539683        17-01-2021
...                  ...               ...          ...               ...
9995        Meghan Cline        Petersport  12701364738        27-04-2022
9996       Jeremiah Pena        Briggsport  15314947645        17-01-2022
9997           Peggy Key    West Joyceport   5201092482        13-01-2022
9998       Evan Humphrey    Camachochester  14652429979        14-04-2020
9999  Melissa Montgomery        Sparkstown  18896829490        27-06-2020

[10000 rows x 4 columns]

In [97]:
data.to_csv(r'D:\EDA\clean_customers_data.csv', index=False) #Convert it to CSV and save it